### ISSUE TITLE
[Bug]: Erro "Area code is not set" ao realizar a instalação via Composer no Magento 2.4.2

### ISSUE THREAD

**Issue by rafaeldeiro** [getnet-adquirencia/payment-magento#30]
### Detalhes de contato

rafaeldeiro@vxcaseloja.com

### O que aconteceu?

No Magento 2.4.2 ocorre o erro "Area code is not set" ao realizar a instalação via Composer.

Instalei sem erros o módulo com o ```composer require```, porém ao executar o comando ```bin/magento setup:upgrade``` ocorre o erro mencionado.

```
In State.php line 153:
                        
  Area code is not set
```

Tenho instalado o módulo FCamara_Getnet, e tentei realizar a instalação com ele ativado e desativado, porém não surtiu nenhum efeito.
Após desativar o módulo Getnet_PaymentMagento e executar novamente os comandos ```setup:upgrade``` e  ```setup:di:compile``` do Magento, nenhum erro ocorre, o que me leva a entender que o erro se encontra realmente no módulo Getnet_PaymentMagento.

### Versão do Magento

2.4.x (Magento >= 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Há logs relavantes sobre o problema?

```shell
Exception Trace ao executar o :upgrade no modo verboso.
In State.php line 153:                                   
  [Magento\Framework\Exception\LocalizedException]  
  Area code is not set                              
   Exception trace:
  at /var/www/magento2/vendor/magento/framework/App/State.php:153
 Magento\Framework\App\State->getAreaCode() at /var/www/magento2/generated/code/Magento/Framework/App/State/Interceptor.php:50
 Magento\Framework\App\State\Interceptor->getAreaCode() at /var/www/magento2/vendor/magento/module-theme/Model/Theme.php:272
 Magento\Theme\Model\Theme->getArea() at /var/www/magento2/vendor/magento/framework/View/File/Collector/Base.php:68
 Magento\Framework\View\File\Collector\Base->getFiles() at /var/www/magento2/vendor/magento/framework/View/File/Collector/Decorator/ModuleOutput.php:59
```

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Eu não consegui instalar o módulo

**Comment by elisei** [comment]
Olá @Rafael-Deiro tudo bem?

A versão 2.4.2 foi a utilizada no desenvolvimento do módulo, então estou bem seguro que não é nada do módulo, o que me indica seguirmos para outras ações.

Por favor teste as sequintes ações:
- verificar se o opcache está ativo, caso esteja restartar o php
- remover o FCamara (remover pelo composer e não só desativar)

Só então tente recopilar novamente por favor!

**Comment by elisei** [comment]
Olá @Rafael-Deiro

Você ainda precisa de apoio ou podemos fechar esse issue?

**Comment by RoninX2** [comment]
Olá @elisei estou com esse mesmo problema.... sempre quando faço o download pelo composer, e vou rodar o setup:upgrade da erro de 

In State.php line 153:
                        
  Area code is not set
  
  Estou utilizando o magento 2.4.3-p2. Quando removo o módulo, o magento funciona corretamente. Remove da pasta vendor e excluo o require do composer.json, o site volta a funcionar normalmente.

**Comment by rafaeldeiro** [comment]
@elisei desculpe pela demora, foi a correria do go-live. Vou testar reiniciar o fpm ou remover o FCamara e passo um feedback.
@RoninX2 chegou a testar o que o elisei recomendou?

**Comment by rafaeldeiro** [comment]
@elisei mesmo reiniciando o fpm e removendo o módulo da FCamara, o mesmo problema persiste

**Comment by elisei** [comment]
@Rafael-Deiro Sua versão também é a 2.4.3-p2?

O desenvolvimento foi na 2.4.3 e depois nas 2.4.4 e na 2.4.5, pode ser algo específico da "p2". Quando possível por favor me oriente para que eu possa seguir com os testes aqui.

**Comment by elisei** [comment]
Oi @Rafael-Deiro e @RoninX2 

Consegui reproduzir o erro e já lançamos a correção na tag 102.2.16!
