### ISSUE TITLE
Qual as urls de CallBack?

### ISSUE THREAD

**Issue by ricardopantani** [getnet-adquirencia/payment-magento#31]
### O que aconteceu?

Olá, Poderia informar quais as URLs de CallBack para configuração no Painel da Getnet?

### Versão do Magento

2.4.x (Magento >= 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Eu não consegui configurar o módulo

**Comment by elisei** [comment]
Olá @ricardopantani 

O callback estará disponível na sessão de configuração do módulo em Notificações:
![image](https://user-images.githubusercontent.com/1786389/190402515-156b4ab4-e5d2-4fbd-829a-7dda94fdcc57.png)

Ele é criado a partir do seu seller id!

:warning: Atenção: Para receber CallBack é necessário enviar email para solicitar liberação da url, para [suporte.edigital@getnet.com.br](mailto:suporte.edigital@getnet.com.br).

**Comment by ricardopantani** [comment]
> Olá @ricardopantani
> 
> O callback estará disponível na sessão de configuração do módulo em Notificações: ![image](https://user-images.githubusercontent.com/1786389/190402515-156b4ab4-e5d2-4fbd-829a-7dda94fdcc57.png)
> 
> Ele é criado a partir do seu seller id!
> 
> ⚠️ Atenção: Para receber CallBack é necessário enviar email para solicitar liberação da url, para [suporte.edigital@getnet.com.br](mailto:suporte.edigital@getnet.com.br).


Obrigado pela resposta, [elisei]
Mais e as urls de callback de pagamento, callback de credito  e callback recorrente?

**Comment by elisei** [comment]
Olá @ricardopantani 

Em pagamento você coloca o PIX. Em crédito não tem callback o status é sincrono no pedido e recorrente não é um serviço disponível no módulo!

**Comment by ricardopantani** [comment]
> Olá @ricardopantani
> 
> Em pagamento você coloca o PIX. Em crédito não tem callback o status é sincrono no pedido e recorrente não é um serviço disponível no módulo!

Obrigado!
