### ISSUE TITLE
[Bug]: Erro ao tokenizar cartão

### ISSUE THREAD

**Issue by rafaeldeiro** [getnet-adquirencia/payment-magento#32]
### Detalhes de contato

rafaeldeiro@vxcaseloja.com

### O que aconteceu?

Ao tokenizar o cartão no endpoint `V1/guest-carts/:cartId/generate-credit-card-number-token`, quando o endpoint da Getnet retorna erro (ex. HTTP 401), ocorre um TypeError não capturado no `method_renderer/getnet_paymentmagento_cc.js:246` pois o JS tenta ler a propriedade `response[0].message.text`, porém a response é `[{"success": 0}]`.

Esse erro bloqueia o checkout pois o JS não consegue remover o blockLoader da tela.

### Versão do Magento

2.4.x (Magento >= 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Há logs relavantes sobre o problema?

```shell
[payment.log]
[2022-10-11 18:22:45] main.DEBUG: array (
  'url' => 'https://api-homologacao.getnet.com.br/v1/tokens/card',
  'response' => '{   "message": "Unauthorized",   "name": "GatewayAuthenticationOAuth2ServiceError",   "status_code": 401,   "details": [     {       "status": "DENIED",       "error_code": "AUTHENTICATION-401",       "description": "Unauthorized",       "description_detail": "Invalid client credentials"     }   ] }',
) [] []

---

[JS Console Output]
Uncaught TypeError: Cannot read properties of undefined (reading 'text')
    at Object.<anonymous> (getnet_paymentmagento_cc.js:246:95)
```

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Nenhum cliente consegue realizar um pagamento

**Comment by rafaeldeiro** [comment]
@elisei propus uma solução no PR #33, testei na minha loja, na versão 2.4.2 e resolveu.

**Comment by elisei** [comment]
@Rafael-Deiro muito obrigado! :dancers: 

Aprovado e já merchado na tag 102.2.18!
