### ISSUE TITLE
[Bug]: Problemas no Cancelamento D0

### ISSUE THREAD

**Issue by rafaeldeiro** [getnet-adquirencia/payment-magento#36]
### Detalhes de contato

rafaeldeiro@vxcaseloja.com

### O que aconteceu?

O módulo está utilizando o endpoint incorreto para o cancelamento de pagamentos em D0 (no mesmo dia), portanto, não conseguimos cancelar pedidos diretamente pelo Magento.

Em contato com o suporte da Getnet o problema foi esclarecido.
O módulo utiliza o endpoint ```/v1/payments/cancel/request``` para todos os cancelamentos, porém deveria utilizar o endpoint ```/v1/payments/credit/{payment_id}/cancel``` para cancelamentos no mesmo dia (D0)

Print da resposta do suporte:
![image](https://user-images.githubusercontent.com/40615781/206253621-eefdbbe7-8578-4d92-a8c7-c8420bf9b610.png)

### Versão do Magento

2.4.x (Magento >= 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Uma das formas de pagamento não está funcionando

**Comment by rafaeldeiro** [comment]
@elisei estou trabalhando em uma correção localmente e assim que validar, envio um PR

**Comment by elisei** [comment]
@Rafael-Deiro qualquer nos informe por favor!

**Comment by elisei** [comment]
@Rafael-Deiro Você conseguiu realizar esse processo?

Caso não eu vou assumir essa ação!

**Comment by elisei** [comment]
@Rafael-Deiro 

Eu apliquei um ajuste para o d0 por favor atualize a versão!

**Comment by elisei** [comment]
@Rafael-Deiro  Conforme analise realizada, foi detectado que o método cofre não é um produto ativo para a conta do vendedor. Foi orientado a deixar o método desativar e solicitar a liberação do recurso com o atendimento da Getnet.
