### ISSUE TITLE
[Bug]: Erro na validação de cartão

### ISSUE THREAD

**Issue by eurafaellisboa** [getnet-adquirencia/payment-magento#38]
### Detalhes de contato

eurafaellisboa@gmail.com

### O que aconteceu?

Instalei o módulo, consigo finalizar em Sandbox, via PIX e boleto, mas não com cartão de crédito.

Tanto em sandbox, quanto em produção, aparece a seguinte mensagem, ao inserir um número de cartão de crédito (válido, testado com 3 cartões diferentes)

Por favor insira um número de tipo de cartão de crédito válido.

Não sei se errei em alguma coisa, alguém consegue me dar uma luz sobre o que pode estar acontecendo?

### Versão do Magento

2.3.x (Magento >= 2.3.0 e < 2.4.0)

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Eu não consegui configurar o módulo

**Comment by elisei** [comment]
Olá @eurafaellisboa tudo bem?

Você tem algum outro módulo de pagamento instalado, mesmo que não ativo, na aplicação?

**Comment by elisei** [comment]
@eurafaellisboa 

Estou fechando o issue, qualquer coisa por favor reabra.
