### ISSUE TITLE
[Bug]: Dúvida: Aumentar tempo do QR Code

### ISSUE THREAD

**Issue by eurafaellisboa** [getnet-adquirencia/payment-magento#42]
### Detalhes de contato

eurafaellisboa@gmail.com

### O que aconteceu?

Olá pessoal, na verdade é uma dúvida.

Existe uma maneira de aumentar o tempo de validade do QR Code?

Por padrão está 3 minutos, queria deixar 59min.

Obrigado desde já.

### Versão do Magento

2.3.x (Magento >= 2.3.0 e < 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Eu não consegui configurar o módulo

**Comment by elisei** [comment]
Oi @eurafaellisboa 

Infelizmente não tem como, mas está rolando um projeto interno na getnet para aumentar esse tempo, porém eu não tenho notícias de quando ocorrerá.

**Comment by eurafaellisboa** [comment]
Opa @elisei 

Que pena. Mas de qualquer forma, obrigado pelo retorno.

Ficamos no aguardo.
