### ISSUE TITLE
[Dúvida]: Muitas compras "Recusadas" 

### ISSUE THREAD

**Issue by eurafaellisboa** [getnet-adquirencia/payment-magento#43]
### Detalhes de contato

eurafaellisboa@gmail.com

### O que aconteceu?

Pessoal, bom dia.

Tenho um cliente que está recebendo diversas "Falhas de Pagamento" durante o dia, com pedidos via cartão de crédito.

 No e-mail de falha de pagamento, vem "A Transação foi recusada. Por favor tente novamente mais tarde."

Alguns clientes fecham o pedido normal, mas acho que 50% não consegue.

Será que é o antifraude? O estranho é que tem gente que consegue fazer o pedido normalmente e outros não.

Eu mesmo, toda vez que testo (pra ver o request e response) finaliza normalmente 

Obrigado desde já

### Versão do Magento

2.3.x (Magento >= 2.3.0 e < 2.4.0)

### O problema pode ter alguma relação com um navegador específico?

Não tem relação com o navegador usado

### Meu log não contém informações confidênciais

- [X] Eu não estou enviando dados que viole a privacidade do cliente ou da loja.

### Qual a severidade do problema?

Uma das formas de pagamento não está funcionando

**Comment by elisei** [comment]
@eurafaellisboa 
É provavel que seja o antifraude, mas por favor ative o log e nos envie que analisamos detalhadamente.

**Comment by eurafaellisboa** [comment]
@elisei mesmo em produção, ativo o depurador?

**Comment by elisei** [comment]
@eurafaellisboa temporariamente sim.

**Comment by eurafaellisboa** [comment]
Segue o log @elisei 

[2023-03-15 15:29:19] main.DEBUG: array (
  'url' => 'https://api.getnet.com.br/v1/payments/credit',
  'request' => '{"seller_id":"SUPRMIDO","amount":12853,"currency":"BRL","order":{"order_id":"SUPRMIDO","sales_tax":0},"customer":{"customer_id":"SUPRMIDO","first_name":"SUPRMIDO","last_name":"SUPRMIDO","name":"SUPRMIDO","email”:”SUPRMIDO,”phone_number":"SUPRMIDO","billing_address":{"postal_code":"SUPRMIDO","street":"SUPRMIDO","number":"690","district":"T&T Im\\u00f3veis e Neg\\u00f3cios","complement":"Centro","city":"SUPRMIDO","state":"SC","country":"BR"},"document_type":"CPF","document_number":"SUPRMIDO"},"shippings":[{"first_name":"SUPRMIDO","name":"SUPRMIDO","email":"SUPRMIDO","phone_number":"SUPRMIDO","shipping_amount":2185,"address":{"postal_code":"SUPRMIDO","street":"SUPRMIDO","number":"690","district":"T&T Im\\u00f3veis e Neg\\u00f3cios","complement":"Centro","city":"SUPRMIDO","state":"SC","country":"BR"}}],"device":{"ip_address":"SUPRMIDO","device_id":"59f0ed22a05e907ea3a3477e198be6de"},"credit":{"save_card_data":"true","delayed":false,"transaction_type":"FULL","number_installments":"1","soft_descriptor":"Acquaflora","dynamic_mcc":"123","card":{"number_token":null,"brand":"Visa","cardholder_name":"SUPRMIDO","security_code":"SUPRMIDO","expiration_month":"06","expiration_year":"SUPRMIDO"}}}',
  'response' => '{
    "message": "Bad Request",
    "name": "GatewayTokenizationServiceError",
    "status_code": 400,
    "details": [
        {
            "status": "DENIED",
            "error_code": "TOKENIZATION-400",
            "description": "Bad Request",
            "description_detail": "Missing token card"
        }
    ]
}',

**Comment by elisei** [comment]
@eurafaellisboa 
Esse é um pgto por vault?
Se sim pode testar uma compra sem fazer uso dele?

**Comment by eurafaellisboa** [comment]
Não sei se é por vault, foi uma tentativa de um cliente que deu erro

Como faço para ter essa info?

**Comment by elisei** [comment]
Esse foi via vault sim!

O problema ai parece ser o token desse vault está agora inválido. 

Vamos prosseguir a analise pelo email? brunoelisei@o2ti.com

**Comment by eurafaellisboa** [comment]
Te mandei email @elisei

**Comment by elisei** [comment]
@eurafaellisboa não recebi até agora :'(

**Comment by eurafaellisboa** [comment]
@elisei consegue me mandar e eu respondo?

**Comment by elisei** [comment]
Sim mas o qual o seu email? @eurafaellisboa

**Comment by eurafaellisboa** [comment]
eurafaellisboa@gmail.com

**Comment by elisei** [comment]
@eurafaellisboa  Conforme analise realizada, foi detectado que o método cofre não é um produto ativo para a conta do vendedor. Foi orientado a deixar o método desativar e solicitar a liberação do recurso com o atendimento da Getnet.
