### ISSUE TITLE
Necessário Decrypt (Admin salva com Magento\Config\Model\Config\Backend\Encrypted)

### ISSUE THREAD

**Issue by michelsilva04** [getnet-adquirencia/payment-magento#44]
https://github.com/Getnet-Brasil/payment-magento/blob/46b0b72903d788332ea1ec48219933fa7b1d9ab5/Gateway/Config/Config.php#L197

**Comment by elisei** [comment]
olá @ssuhss 

Quando necessário a Magento desencripta a informação, mas você não pode acessar diretamente.

**Comment by michelsilva04** [comment]
Olá Elisei, o modulo não está fazendo o decrypt, quando salvo novas credenciais pelo admin quebra o refreshToken pois ele tenta utilizar o clietId e clientSecret encrypted.

**Comment by elisei** [comment]
Olá @ssuhss 

Por gentileza, descreva os processos em etapas que possamos reproduzir por favor.

Por aqui em um ambiente:
- php 8.2
- magento 2.4.6
- módulo versão 103.0.9

O fluxo de refresh ocorre sem nenhum problema:
![image](https://github.com/Getnet-Brasil/payment-magento/assets/1786389/1ba067a2-d36a-4077-9631-4d05b9fdc6d8)

**Comment by michelsilva04** [comment]
Desculpa, encontrei o erro, é um plugin no cliente manipulando o "scopeConfig->getValue(...".
