### ISSUE TITLE
[Bug]: Valor mínimo da parcela em pedidos no admin

### ISSUE THREAD

**Issue by yurirn** [getnet-adquirencia/payment-magento#46]
### Contact details

yurirneves@gmail.com

### What happened?

Tenho um cliente que faz alguns pedidos direto no admin, e na hora de carregar as parcelas, não esta aplicando a mesma regra de valor mínimo de parcelas nem a quantidade máxima de parcelas que se aplica no front

### Magento version

2.4.x (Magento >= 2.4.0)

### What version of php?

PHP 7.4

### My log does not contain confidential information

- [X] I am not sending data that violates the privacy of the customer or the store.

### What is the severity of the problem?

One of the payment methods is not working

**Comment by elisei** [comment]
Olá @yurirn  as regras se aplicam somente ao frontend no backend o próprio administrador tem que controlar. isso é proposital pois muitos oferecem regras diferentes em um atendimento "humano".

**Comment by yurirn** [comment]
entendi, obrigado
