### ISSUE TITLE
[Question]: Duvidas sobre o fluxo de cartão de credito

### ISSUE THREAD

**Issue by jsrjunior** [getnet-adquirencia/payment-magento#50]
### Dados de Contato

junior.s360@hotmail.com

### Qual a sua dúvida?

Olá, fiz a instalação do modulo. Estou estendendo ele para GraphQL, fique com duvidas sobre o funcionamento, fiz o teste com a criação de alguns pedidos, preencho as informações, e no caso, o pedido aparentemente não esta sendo enviado para transacionar, ficando apenas com o status de novo pedido. Conferi se havia um cron que verifica pedidos pendentes, ou endpoints, mas não consegui entender bem.

Via verifiquei na sales_payment que o cartão é tockenizado, mais não é transacionado. 

Se puderem me ajudar.
Obrigado!

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

**Comment by elisei** [comment]
Oi @jsrjunior 

O pagamento chegou a gerar o payment.log?

Qual a versão do módulo está usando?

**Comment by jsrjunior** [comment]
Oi @elisei, tudo bem?

Estou usando a versão 101, não gerou o payment.log.

**Comment by elisei** [comment]
Pode me passar a versão completa por favor, você a obtém pelo composer. Apenas a versão mais recente trás o log habilitado por padrão, por isso o questionamento.

**Comment by elisei** [comment]
Comando completo:

composer show getnetadquirencia/payment-magento --all

**Comment by jsrjunior** [comment]
Me enganei, estou usando a versão: 103.0.8.

O magento aqui é a versão 2.4.2, nesse caso tenho que fazer o downgrade, correto?

**Comment by elisei** [comment]
Entendi, atualize o módulo e veja se aparece algo no payment.log

**Comment by jsrjunior** [comment]
Infelizmente não consegui, problemas com dependências, a versão do PHP do projeto é a 7.4.33, o requerimento da versão é o 8

**Comment by elisei** [comment]
Execute usando o:

composer require getnetadquirencia/payment-magento:~101 --ignore-platform-req=php

**Comment by jsrjunior** [comment]
Não consegui mesmo assim:
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires getnetadquirencia/payment-magento ~101, found getnetadquirencia/payment-magento[dev-NovaVersao, dev-Magento@2.3, dev-Magento@2.3.7, dev-Magento@2.4, dev-Magento@2.4.6, 2.x-dev, 100.1.0, ..., 100.2.11, 102.0.9, ..., 102.3.14-p2, 103.0.1, ..., 103.3.15] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by elisei** [comment]
Rode assim:
composer require getnetadquirencia/payment-magento:101.0.33

**Comment by jsrjunior** [comment]
Assim também não foi,

./composer.json has been updated
Running composer update getnetadquirencia/payment-magento
Loading composer repositories with package information
In Laminas\DependencyPlugin\DependencyRewriterV2::onPrePoolCreate
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires getnetadquirencia/payment-magento 101.0.33, found getnetadquirencia/payment-magento[dev-NovaVersao, dev-Magento@2.3, dev-Magento@2.3.7, dev-Magento@2.4, dev-Magento@2.4.6, 2.x-dev, 100.1.0, ..., 100.2.11, 102.0.9, ..., 102.3.14-p2, 103.0.1, ..., 103.3.15] but it does not match the constraint.

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

**Comment by jsrjunior** [comment]
Qual o fluxo deveria ser disparado para aprovação do pedido?

**Comment by elisei** [comment]
Tá estranho, lamininas é uma dependência de Magento 2.4.6+ se o seu Magento e 2.4.2 ela não faz sentido nem se aplica. Você tem certeza quanto a sua versão?

**Comment by elisei** [comment]
Nenhum, o processo é síncrono, gerou o pedido já gera a resposta da getnet.

**Comment by jsrjunior** [comment]
Então, ele gera o pedido, grava o json com informações do cartão de pagamento, token e tudo mais.
Mas o status retornado é apenas novo pedido, mesmo quando coloco um cartão que deveria vir invalido.

Acabei de rodar bin/magento --version
Magento CLI 2.4.2

**Comment by elisei** [comment]
Vamos marcar um reunião por vídeo amanhã?

Por favor me procure em brunoelisei@o2ti.com e me informe 3 sugestões de horários.

**Comment by elisei** [comment]
@jsrjunior 

Apenas para registro, foi detectada uma customização da loja que estava gerando esse comportamento.
