### ISSUE TITLE
[Question]: Não consigo registrar na pagina de sandbox para testar o modulo

### ISSUE THREAD

**Issue by redati** [getnet-adquirencia/payment-magento#53]
### Dados de Contato

contato@decoraonline.com.br

### Qual a sua dúvida?

Não consigo registrar no site da getnet, na pagina de sandbox, para poder testar o modulo.

### Versão da Magento/Adobe

2.4.6+ (Magento/Adobe >= 2.4.6)

**Comment by elisei** [comment]
@redati 

A sandbox foi desativada, agora é possível apenas o ambiente de homologação, para ter acesso a ele, por favor entre em contato com suporte.edigital@getnet.com.br

**Comment by redati** [comment]
certo, valeu.
