### ISSUE TITLE
[Question]: Tem suporte ao 3DS?

### ISSUE THREAD

**Issue by albertobraschi** [getnet-adquirencia/payment-magento#56]
### Qual a sua dúvida?

o plugin da getnet pra m2, tem recurso, suporte, ao 3ds?

### Versão da Magento/Adobe

2.4.6+ (Magento/Adobe >= 2.4.6)

**Comment by elisei** [comment]
Olá @albertobraschi,

No momento não tem o recurso, mas recomendo falar com o comercial da sua equipe para analisarem isso!

**Comment by rafaneri** [comment]
@elisei recebi a documentação da getnet para implementar o 3DS no nosso site, porém o mais importante que era o arquivo getnet_3DS.js não veio. Onde acho esse bendito arquivo? Já rodei a documentação toda e nada de encontrar.
