### ISSUE TITLE
[Question]: Como cancelar / estornar uma transação pix? 

### ISSUE THREAD

**Issue by FVitor7** [getnet-adquirencia/payment-magento#58]
### Dados de Contato

fabvitor2010@gmail.com

### Qual a sua dúvida?

Existe a possibilidade de estornar uma transação pix pela api?
Tentei consultar a documentação, porem a mesma está  com problemas. https://developers.getnet.com.br/api

### Versão da Magento/Adobe

2.3.x (Magento/Adobe >= 2.3.0 e < 2.4.0)

**Comment by elisei** [comment]
@FVitor7 não existe esse recurso na API da Getnet, por isso não tem como ser feito no módulo!
