### ISSUE TITLE
[Question]: Can't find version 103.3.14

### ISSUE THREAD

**Issue by guilhermemap** [getnet-adquirencia/payment-magento#59]
### Dados de Contato

guilherme@acheipneus.com.br

### Qual a sua dúvida?

I can't find version 103.3.14 of this module. We have it running in a project and can't make a new environment to debug because the version is missing now. What happened?

### Versão da Magento/Adobe

2.4.0 até 2.4.5 (Magento/Adobe >= 2.4.0 e < 2.4.5)

**Comment by elisei** [comment]
Ela foi descontinuada, por favor siga para as versões mais recentes!

**Comment by guilhermemap** [comment]
A 103.3.14 (que está funcionando em produção) usa a api v1, tentamos testar com outra versão mais nova que usa a api v2 e não deu certo.
Vi que outras versões anteriores ainda estão no github, pq apagar especificamente a 3.14?

**Comment by elisei** [comment]
Olá @guilhermemap se houve algum problema com a v2 por favor nos indique. Todas as versões v1 foram apagadas exatamente para migrar para a v2.

Abra um novo issue e reporte o problema apresentado com a v2 para que possamos lhe apoiar!
