### ISSUE TITLE
[Question]: Erro 87 da API v2

### ISSUE THREAD

**Issue by guilhermemap** [getnet-adquirencia/payment-magento#60]
### Dados de Contato

guilherme@acheipneus.com.br

### Qual a sua dúvida?

![image](https://github.com/user-attachments/assets/8a152b4c-e36b-4e0c-b650-99e3d3ede37c)
A access_token é gerada corretamente (pelo módulo e testando via postman), mas a requisição que deveria gerar a transação dá esse erro 87 ("Ocorreu um erro junto à instituição financeira responsável pelo pagamento"). 

Só conseguimos ver o erro debugando ou pelo Postman porque no módulo o erro que dá é na linha 100 do arquivo /home/guilherme/MagentoCloud/app/code/Getnet/PaymentMagento/Gateway/Response/Pix/TxnIdHandler.php ao tentar ler propriedade 'additional_data' da resposta.

### Versão da Magento/Adobe

2.4.6+ (Magento/Adobe >= 2.4.6)

**Comment by elisei** [comment]
@guilhermemap precisar acionar o suporte e-digital, o email é suporte.edigital@getnet.com.br, pois de fato sua transação está sendo recusada na v2, indique o payload e o endpoint no email, pode me colocar em cópia brunoelisei@o2ti.com e não esquecer de incluir o o seller id!
